name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull shrimp0000/my-app:latest
    - name: Delete Old docker container
      run: sudo docker rm -f my-app-container || true
    - name: Run Docker container
      run: sudo docker run -d --name my-app-container -p 80:80 shrimp0000/my-app:latest